sudo: required

os:
  - linux

language: c
dist: xenial

matrix:
  include:
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y
  - choosenim $CHANNEL

script:
  - nimble -y test
